#!/bin/bash
# $Id: rshutdown,v 1.2 2015/12/11 18:40:40 fulford Exp $
# $Source: /src/merlin/usr/local/etc/RCS/rshutdown,v $
# $Revision: 1.2 $
# Author C W Fulford.
# Copyright 2015 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
ver=`echo "$Id: rshutdown,v 1.2 2015/12/11 18:40:40 fulford Exp $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.2 $ $Date: 2015/12/11 18:40:40 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done

config=${config:-/usr/local/etc/${cmd}.cf
[ -r $config ]||{echo $cmd: Can't find $config;exit 1}
eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ]*[^#].*/p}"`
hosts="10.0.0.4 10.0.0.5"
[ -n "$hosts" ] ||  {
	hosts=`nmap -oG - 10.0.0.3-50 |awk  '/22\/open/ {print $2}'`
}
myips=`sudo  /sbin/ifconfig -a|awk '/inet /{print $2}'`
for h in $hosts;do 
	for ip in $myips ;do
		[ $h == $ip ] &&  continue 2
	done
	ssh $h 'sudo shutdown -t 30  "URGENT total power loss. Shutdown in 30 seconds"'
done
sleep 3
shutdown -t 30  "URGENT total power loss. Shutdown in 30 seconds"

